apiVersion: v1
kind: Secret
metadata:
  name: app-secret
type: Opaque
stringData:
  app-config: |
    environment: prod
    db-url: mysql.prod.com
    db-username: kahootali
    db-password: "123456"
  username: ali-kahoot
  password: dice
data:
  name: YWxp #base64 encoding of ali
---
apiVersion: v1
kind: Secret
metadata:
  name: app-env-secret
  namespace: default
stringData:
  USERNAME: kahootali
  PASSWORD: "123456"
---
# kubectl create secret generic app-secret-config --from-file app-secret-config