apiVersion: v1
kind: Pod
metadata:
  name: secret-env
spec:
  containers:
  - name: db
    image: ubuntu
    args: [/bin/sh, -c,'i=0; while true; do echo "$i: $(date)"; i=$((i+1)); sleep 1s; done']
    envFrom:
      - secretRef:
          name: app-env-secret
    env:
      - name: SECRET_USERNAME
        valueFrom:
          secretKeyRef:
            name: app-secret
            key: username
      - name: SECRET_PASSWORD
        valueFrom:
          secretKeyRef:
            name: app-secret
            key: password
  restartPolicy: Never