apiVersion: v1
kind: Pod
metadata:
  name: demo-envr
spec:
  containers:
  - name: envtest
    image: busybox
    args: [/bin/sh, -c,'i=0; while true; do sleep 1s; done']
    ports:
    - containerPort: 8080
    envFrom:
      - configMapRef:
          name: app-env-config
    env:
    - name: INSTRUCTOR1
      valueFrom:
        configMapKeyRef:
          name: app-config
          key: instructor-1
    - name: INSTRUCTOR2
      valueFrom:
        configMapKeyRef:
          name: app-config
          key: instructor-2