apiVersion: v1
kind: Pod
metadata:
  name: demo-config-volume
spec:
  containers:
  - name: demo-cont
    image: busybox
    args: [/bin/sh, -c,'i=0; while true; do sleep 1s; done']
    volumeMounts:
    - name: config-volume
      mountPath: /etc/config
  volumes:
  - name: config-volume
    configMap:
      name: app-config
  restartPolicy: Never