apiVersion: v1
kind: Namespace
metadata:
  name: <insert-namespace-name-here>
---  
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ghost
  namespace: <insert-namespace-name-here>
spec:
  replicas: 1
  selector:
    matchLabels:
      tier: ghost
      app: dice
  template:
    metadata:
      labels:
        tier: ghost
        app: dice
    spec:
      containers:
      - name: ghost
        image: ghost

---
apiVersion: v1
kind: Service
metadata:
  name: ghost
  namespace: <insert-namespace-name-here>
spec:
  type: NodePort
  selector:
    tier: ghost
    app: dice
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 2368
    nodePort: <PORT>
---