apiVersion: v1
kind: Pod
metadata:
  name: busybox-with-curl
  labels:
    app: busybox-with-curl
spec:
  containers:
  - name: busybox-with-curl
    image: kahootali/busybox-with-curl
    args: [/bin/sh, -c,'i=0; while true; do sleep 1s; done']
