apiVersion: apps/v1
kind: Deployment
metadata:
  name: counter
  labels:
    app: counter
  annotations:
    class: dice
spec:
  replicas: 3
  selector:
    matchLabels:
      app: counter
  template:
    metadata:
      labels:
        app: counter
    spec:
      containers:
      - name: counter
        image: ubuntu
        args: [/bin/sh, -c,'i=0; while true; do echo "$i: $(date) Hi $(INSTITUTE) students, Are you learning well?"; i=$((i+1)); sleep 10s; done']
        env:
        - name: INSTITUTE
          value: Dice Analytics