apiVersion: v1
kind: Service
metadata:
  name: golang-api
spec:
  type: NodePort
  selector:
    app: application
    type: pod
  ports:
  - protocol: TCP
    port: 9090
    targetPort: 8080
    nodePort: 32000