apiVersion: v1
kind: Pod
metadata:
  name: counter-multi
spec:
  containers:
  - name: counter-1
    image: busybox
    args: [/bin/sh, -c,'i=0; while true; do echo "$i: $(date) 1st Container in Multi-Pod "; i=$((i+1)); sleep 5s; done']
  - name: counter-2
    image: busybox
    args: [/bin/sh, -c,'i=0; while true; do echo "$i: $(date) 2nd Container in Multi-Pod"; i=$((i+1)); sleep 10s; done']
  - name: counter-3
    image: busybox
    args: [/bin/sh, -c,'i=0; while true; do echo "$i: $(date) 3rd Container in Multi-Pod"; i=$((i+1)); sleep 15s; done']