apiVersion: apps/v1
kind: Deployment
metadata:
  name: pod-with-secret
  labels:
    app: pod-with-secret
  annotations:
    reloader.stakater.com/auto: "true"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pod-with-secret
  template:
    metadata:
      labels:
        app: pod-with-secret
    spec:
      containers:
      - name: db
        image: busybox
        args: [/bin/sh, -c,'i=0; while true; do echo "$i: $(date)"; i=$((i+1)); sleep 1s; done']
        volumeMounts:
        - name: myvolume
          mountPath: "/etc/secrets"
          readOnly: true
      volumes:
      - name: myvolume
        secret:
          secretName: test-secret
---
apiVersion: v1
kind: Secret
metadata:
  name: test-secret
type: Opaque
stringData:
  username: ali-kahoot
  password: dice4
data:
  name: YWxp